[book]
authors = ["Gyuho Lee"]
language = "en"
multilingual = false
src = "src"
title = "Learn"

[output.html]
curly-quotes = true
edit-url-template = "https://github.com/gyuho/learn/edit/main/{path}"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/gyuho/learn"
mathjax-support = true

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
